### ISSUE TITLE
heroku連携

### ISSUE THREAD

**Issue by ouchi2501** [rosso357/GranbuleBot#1]
このbotをheroku上で動かしたいので[heroku](https://jp.heroku.com/)との連携を実施する

**Comment by ouchi2501** [comment]
一応実施手順を下記に記載

```
# heroku-cliのinstall
brew install heroku/brew/heroku
# heroku login
heroku login
# heroku remote 設定
heroku git:remote -a granblue-bot
# herokuへのdeploy
git push heroku master
```

**Comment by ouchi2501** [comment]
deployで失敗
```
~/g/GranbuleBot  (master) ❯❯❯ git push heroku master
Counting objects: 15, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (11/11), done.
Writing objects: 100% (15/15), 17.75 KiB | 0 bytes/s, done.
Total 15 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  0.10.x
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 0.10.x...
remote:        Downloading and installing node 0.10.48...
remote:        Detected package-lock.json: defaulting npm to version 5.x.x
remote:        Bootstrapping npm 5.x.x (replacing 2.15.1)...
remote:
remote: /tmp/build_6be899094692e92fa1f09821a91ada3e/.heroku/node/lib/node_modules/npm/bin/npm-cli.js:79
remote:       var notifier = require('update-notifier')({pkg})
remote:                                                     ^
remote: SyntaxError: Unexpected token }
remote:     at Module._compile (module.js:439:25)
remote:     at Object.Module._extensions..js (module.js:474:10)
remote:     at Module.load (module.js:356:32)
remote:     at Function.Module._load (module.js:312:12)
remote:     at Function.Module.runMain (module.js:497:10)
remote:     at startup (node.js:119:16)
remote:     at node.js:945:3
remote:        npm  installed
remote:
remote: /tmp/build_6be899094692e92fa1f09821a91ada3e/.heroku/node/lib/node_modules/npm/bin/npm-cli.js:79
remote:       var notifier = require('update-notifier')({pkg})
remote:                                                     ^
remote: SyntaxError: Unexpected token }
remote:     at Module._compile (module.js:439:25)
remote:     at Object.Module._extensions..js (module.js:474:10)
remote:     at Module.load (module.js:356:32)
remote:     at Function.Module._load (module.js:312:12)
remote:     at Function.Module.runMain (module.js:497:10)
remote:     at startup (node.js:119:16)
remote:     at node.js:945:3
remote:
remote: /tmp/build_6be899094692e92fa1f09821a91ada3e/.heroku/node/lib/node_modules/npm/bin/npm-cli.js:79
remote:       var notifier = require('update-notifier')({pkg})
remote:                                                     ^
remote: SyntaxError: Unexpected token }
remote:     at Module._compile (module.js:439:25)
remote:     at Object.Module._extensions..js (module.js:474:10)
remote:     at Module.load (module.js:356:32)
remote:     at Function.Module._load (module.js:312:12)
remote:     at Function.Module.runMain (module.js:497:10)
remote:     at startup (node.js:119:16)
remote:     at node.js:945:3
remote: /app/tmp/buildpacks/19862b8792e84bd8421ded4660b92dfd1c41d92e19ac0b38c90301adc8ae3e0bd512fa01998af18fc2f0d31a157e9c82e8fdceba1a05e5d29adb8dc2bfaf08e1/lib/failure.sh: line 498: [: : integer expression expected
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (not-found)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json + package-lock)
remote:
remote:        /tmp/build_6be899094692e92fa1f09821a91ada3e/.heroku/node/lib/node_modules/npm/bin/npm-cli.js:79
remote:        var notifier = require('update-notifier')({pkg})
remote:        ^
remote:        SyntaxError: Unexpected token }
remote:        at Module._compile (module.js:439:25)
remote:        at Object.Module._extensions..js (module.js:474:10)
remote:        at Module.load (module.js:356:32)
remote:        at Function.Module._load (module.js:312:12)
remote:        at Function.Module.runMain (module.js:497:10)
remote:        at startup (node.js:119:16)
remote:        at node.js:945:3
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to granblue-bot.
remote:
To https://git.heroku.com/granblue-bot.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/granblue-bot.git'
```

**Comment by ouchi2501** [comment]
nodeのバージョンぽいのでpackege.jsonを変更したところ成功

**Comment by ouchi2501** [comment]
slack設定コマンド
```
$heroku config:set HUBOT_SLACK_TOKEN=@@@@@@@@@@@@@@@
$ heroku config:set HEROKU_URL='https://xxxxxx'
$ heroku config:set HUBOT_SLACK_TEAM='xxxxx'
$ heroku config:set HUBOT_SLACK_BOTNAME='xxxx'
```
